--flagfile=/century/modules/common/data/global_flagfile.txt
# --cloud_server_ip=10.135.252.124
--cloud_server_ip=127.0.0.1
--cloud_server_port=50018
--cloud_mqtt_server_ip=127.0.0.1
--cloud_mqtt_server_port=10005
--cloud_mqtt_username=admin
--cloud_mqtt_password=emqx_2025_Kl
--cloud_mqtt_sub_qos_default=1
--cloud_mqtt_pub_qos_default=1
--cloud_mqtt_sub_qos_overrides={}
--cloud_mqtt_pub_qos_overrides={}
# --cloud_server_port=9999
--vehicle_unique_id=LK1100000PS000002
--vehicle_id=KL001
