--flagfile=/century/modules/planning/conf/planning.conf
--cputhreshold=0.95
--memthreshold=0.85
--diskthreshold=0.95
--diskwarningthreshold=0.85
--lowfreqthreshold=0.5
--kill_ros_sdk_time_diff=20.0
--kill_process_time_diff=180.0
--teb_planning_required_frq=0.2
--monitorlevel=5
--turn_on_monitor=1
--treat_low_freq_as_error=1
--chassis_topic_monitor_switch=1
--control_topic_monitor_switch=1
--planning_topic_monitor_switch=1
--perceptionObstacle_topic_monitor_switch=1
--prediction_topic_monitor_switch=1
--trafficLigth_topic_monitor_switch=1
--localization_topic_monitor_switch=1
--loc_topic_monitor_switch=1
--mems_topic_monitor_switch=1
--mems_status_topic_monitor_switch=1
--radar_topic_monitor_switch=1
--rs_topic_monitor_switch=1
--ultrasonic_topic_monitor_switch=1
--camera_topic_monitor_switch=1
--cubtek_radar_eol_switch=0
--mcloud_topic_monitor_switch=1
--udas_ultrasonic_eol_monitor_switch=0
--imu_raw_topic_monitor_switch=1
--rs_module_name=centerpoint.dag
--transmission_latency_switch=1
--loc_abnormal_status_time=5.0
--other_machine_address=192.168.1.88
--tbox_address=192.168.1.168
--local_address=192.168.1.66
--loc_topic=/century/loc/pose
--localization_topic=/century/loc/pose