
/******************************************************************************
 * Copyright 2017 The Century Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

/**
 * @file
 * @brief Defines the LonController class.
 */

#pragma once

#include <memory>
#include <queue>
#include <string>
#include <vector>

#include "modules/common/configs/proto/vehicle_config.pb.h"

#include "modules/common/filters/digital_filter.h"
#include "modules/common/filters/digital_filter_coefficients.h"
#include "modules/control/common/interpolation_1d.h"
#include "modules/control/common/interpolation_2d.h"
#include "modules/control/common/leadlag_controller.h"
#include "modules/control/common/pid_controller.h"
#include "modules/control/common/trajectory_analyzer.h"
#include "modules/control/controller/controller.h"

/**
 * @namespace century::control
 * @brief century::control
 */
namespace century {
namespace control {

// enum :int control_mode
// {
//   TORQUE_CONTROL = 1;
//   SPEED_CONTROL = 2;
// };
using century::common::Status;
class TorqueTarget {
 public:
  double GetTorqueRequest(void) { return m_torque_request_; };
  double GetAcceleration_i(void) { return m_acceleration_i_; };
  double GetAcceleration_p(void) { return m_acceleration_p_; };
  double GetAcceleration_s(void) { return m_acceleration_s_; };

  double GetkpFinalTorq_V() { return m_kp_final_; };
  double GetkiFinalTorq_V() { return m_ki_final_; };

  void CalculateTorque_V(double TargetAceleration, double axact,
                         std::shared_ptr<DependencyInjector> injector,
                         const ControlConf *control_conf, double ts,
                         common::VehicleParam vehicle_param_,
                         const canbus::Chassis *chassis);

 private:
  void CalcAxDevDeadZone(double &axdev);

  double m_torque_request_ = 1.0;
  double m_acceleration_i_ = 1.0;
  double m_acceleration_p_ = 1.0;
  double m_acceleration_s_ = 1.0;
  double m_kp_final_ = 1.0;
  double m_ki_final_ = 1.0;
};
/// @brief input signals of control
struct input {
  double m_vehicle_speed_ = 0.0;
  double m_vehicle_speedz1_ = 0.0;
  double m_vehicle_accel_ = 0.0;
  double m_act_torque_ = 0.0;
};
/**
 * @class LonController
 *
 * @brief Longitudinal controller, to compute brake / throttle values.
 */
class LonController : public Controller {
 public:
  /**
   * @brief constructor
   */
  LonController();

  /**
   * @brief destructor
   */
  virtual ~LonController();

  /**
   * @brief initialize Longitudinal Controller
   * @param control_conf control configurations
   * @return Status initialization status
   */
  common::Status Init(std::shared_ptr<DependencyInjector> injector,
                      const ControlConf *control_conf) override;

  /**
   * @brief compute brake / throttle values based on current vehicle status
   *        and target trajectory
   * @param localization vehicle location
   * @param chassis vehicle status e.g., speed, acceleration
   * @param trajectory trajectory generated by planning
   * @param cmd control command
   * @return Status computation status
   */
  common::Status ComputeControlCommand(
      const localization::LocalizationEstimate *localization,
      const canbus::Chassis *chassis, const planning::ADCTrajectory *trajectory,
      const planning::AebResult *aeb_result,
      control::ControlCommand *cmd) override;

  double ComputeBrakeCommand(double Axdeviation, double acceleration_cmd,
                             auto debug, double mass);

  /**
   * @brief reset longitudinal controller
   * @return Status reset status
   */
  common::Status Reset() override;

  /**
   * @brief stop longitudinal controller
   */
  void Stop() override;

  /**
   * @brief longitudinal controller name
   * @return string controller name in string
   */
  std::string Name() const override;

 protected:
  bool ComputeLongitudinalErrors(const TrajectoryAnalyzer *trajectory,
                                 const double preview_time, const double ts,
                                 SimpleLongitudinalDebug *debug);

  void GetPathRemain(SimpleLongitudinalDebug *debug);

  //   std::unique_ptr<Interpolation1D> lon_brake_accel_interpolation_;

  //   std::unique_ptr<Interpolation1D> lon_brake_velocity_gain_interpolation_;

 private:
  void SetDigitalFilterPitchAngle(const LonControllerConf &lon_controller_conf);

  void LoadControlCalibrationTable(
      const LonControllerConf &lon_controller_conf);

  void SetDigitalFilter(double ts, double cutoff_freq,
                        common::DigitalFilter *digital_filter);

  void CloseLogFile();

  common::Status SafetyCheck(double preview_time, control::ControlCommand *cmd);

  bool LocationAnomalyCheck(century::common::TrajectoryPoint reference_point,
                            std::string &error_msg,
                            const planning::ADCTrajectory *trajectory_message);

  bool HeadingAnomalyCheck(century::common::TrajectoryPoint reference_point,
                           century::common::PathPoint matched_point,
                           std::string &error_msg);

  bool CheckDataValidity(const double data);

  bool CheckDataValidity(const uint8_t data);

  bool CheckDataValidity(const bool data);

  double CalcSpeedControl(SimpleLongitudinalDebug *debug,
                          control::ControlCommand *cmd,
                          const planning::ADCTrajectory *trajectory_message);

  double UpdateMass(double real_torq, double ego_acce);

  void CheckVehicleCalibration(SimpleLongitudinalDebug *debug,
                               ControlCommand *const cmd);

  bool InputAnomalyDetection(
      const century::common::VehicleStateProvider *vehicle_state,
      const canbus::Chassis *chassis,
      const planning::ADCTrajectory *trajectory_message,
      const century::common::TrajectoryPoint &target_point,
      const century::common::TrajectoryPoint &adc_point,
      std::string &error_msg);

  bool LocalizationAnomalyDetection(
      const century::common::VehicleStateProvider *vehicle_state,
      const canbus::Chassis *chassis,
      const century::planning::ADCTrajectory *trajectory_message);

  inline void ClearQueue(std::queue<double> *q) {
    std::queue<double> empty;
    swap(empty, *q);
  }

  void BrakeTableInit(void);
  bool TrajectoryPointAnomalyDetection(
      const century::common::TrajectoryPoint &target_point);

  bool TrajectoryDataAnomalyDetection(
      const century::planning::ADCTrajectory *trajectory_message);

  void CalcActuator_V(double &TorqueRequest, double &BrakeRequest,
                      double &speed_cmd, double AccelerationDeviation);

  double NearestInterpolated(const std::vector<double> &input_array,
                             const std::vector<double> &target_array,
                             const double &input);

  Status AEBResponse(const century::planning::AebResult *aeb_result,
                      double & spdcmd_ori, ControlCommand *const cmd, double mass_gain);
  
  bool FRDirectionReverseCheck(const canbus::Chassis *chassis,
                               const century::planning::ADCTrajectory *trajectory_message);
  void TorqueRelatedProcessing(const canbus::Chassis *chassis,
                               const century::planning::ADCTrajectory *trajectory_message,
                               SimpleLongitudinalDebug *debug);
  void Torque_s_p_i_cal(const double acceleration_cmd,const double ts,SimpleLongitudinalDebug *debug);
  void DebugInfoPrinting(SimpleLongitudinalDebug *debug);
  Status MonitorAarchState(const double mass_coef,ControlCommand *const cmd);
  void StationSpeedWeightSet(SimpleLongitudinalDebug *debug);
  void TurnSpeedSet(double preview_time, double ts, SimpleLongitudinalDebug *debug);
  void StopSpeedSet(SimpleLongitudinalDebug *debug);
  void PoorLocationAccuracySpeedSet(const localization::LocalizationEstimate *localization);
  void VehicleStartSet(const canbus::Chassis *chassis, control::ControlCommand *cmd);
  void DriveBrakeCal(const double acceleration_cmd, double &BrakeRequest, double &speed_cmd);

  const localization::LocalizationEstimate *localization_ = nullptr;
  const century::planning::AebResult *aeb_result_ = nullptr;
  const canbus::Chassis *chassis_ = nullptr;

  std::unique_ptr<Interpolation2D> control_interpolation_;
  const planning::ADCTrajectory *trajectory_message_ = nullptr;
  std::unique_ptr<TrajectoryAnalyzer> trajectory_analyzer_;

  std::string name_;
  bool controller_initialized_ = false;

  double m_vehicle_mass_ = 23000;

  bool speed_error_straightaway_init_flag_ = false;

  double velocity_compensation_coefficient_ = 1.0;

  std::vector<double> m_deceleration_table_;
  std::vector<double> m_open_cmd_table_;
  std::vector<double> m_velocity_table_;
  std::vector<double> m_spd_gain_table_;

  double previous_acceleration_ = 0.0;
  double previous_acceleration_reference_ = 0.0;
  double m_torque_request_ = 0.0;
  double m_brake_request_ = 0;
  input m_lon_control_input_;
  canbus::Chassis::GearPosition m_target_gear_ = canbus::Chassis::GEAR_DRIVE;
  canbus::Chassis::GearPosition m_target_gear_prvs_ = canbus::Chassis::GEAR_PARKING;
  uint8_t m_stand_still_cont_ = 0;   // time counter of vehicle stillness
  uint32_t m_gear_change_cont_ = 0;  // time counter of gear station changed
  bool m_engine_control_enable_ = true;
  bool m_brake_control_enable_ = false;
  double m_check_fail_spd_tar_ = 0.0;
  double m_decel_failed_check_ = 0.0;
  double m_time_start_ = 0.0;

  double m_ego_acceleration_ = 0;
  bool m_time_check_first_b_ = false;
  
  double min_response_wheel_speed_ = 0.2778; // 1kmh = 0.2778m/s. minimum response wheel speed for chassis control.
  double weight_speed_control_ = 1.0;    
  double weight_station_control_ = 1.0;
  double traj_length_front_total_ = 0.0;
  bool flag_vehicle_takeoff_ = false; 
  struct CtrlCmd {
    double throttle;
    double brake;
  };
 
  TorqueTarget m_torque_target_;

  PIDController speed_pid_controller_;
  PIDController station_pid_controller_;
  PIDController brake_pid_controller_;
  PIDController torque_pid_controller_;
  PIDController station_pid_speed_controller_;  // used for speed control;

  LeadlagController speed_leadlag_controller_;
  LeadlagController station_leadlag_controller_;

  FILE *speed_log_file_ = nullptr;

  common::DigitalFilter digital_filter_pitch_angle_;

  common::DigitalFilter mass_lpfilter;

  common::DigitalFilter speed_lpfilter_;

  common::DigitalFilter chassis_spd_lpfilter_;
  common::DigitalFilter local_spd_lpfilter_;
  common::DigitalFilter vel_compen_lpfilter_;
  common::DigitalFilter axact_lpfilter_;

  common::DigitalFilter torq_lpfilter_;

  const ControlConf *control_conf_ = nullptr;

  // vehicle parameter
  common::VehicleParam vehicle_param_;

  std::shared_ptr<DependencyInjector> injector_;

  bool f_or_r_direction_reverse_state_ = false;
  double path_remain_ = 0;
  double t_speedcmd_d_ = 0;
  double t_speed_k1_ = 0;
};
double interplation(uint8_t size, double *parx, double *pary, double x) {
  uint8_t t_SegmentIndex_ub = 0U;

  // ----------------- end temporary variables -----------------//

  while ((size > t_SegmentIndex_ub) && (x > parx[t_SegmentIndex_ub])) {
    t_SegmentIndex_ub++;
  }

  double t_Y_d = 0.0f;
  if (size == t_SegmentIndex_ub) {
    t_Y_d = pary[size - (uint8_t)1];  // PRQA S 3711 EOF //PRQA S 3137 EOF
  } else if (0U == t_SegmentIndex_ub) {
    t_Y_d = pary[0];
  } else {
    double t_Divisor_d = 0.0;
    t_Divisor_d =
        parx[t_SegmentIndex_ub] - parx[t_SegmentIndex_ub - (uint8_t)1];
    if (1e-6 < abs(t_Divisor_d)) {
      double t_Sub1_d = 0.0;
      t_Sub1_d = x - parx[t_SegmentIndex_ub - (uint8_t)1];

      double t_Sub2_d = 0.0;

      t_Sub2_d = pary[t_SegmentIndex_ub] - pary[t_SegmentIndex_ub - 1U];
      t_Y_d =
          (t_Sub1_d * t_Sub2_d) / t_Divisor_d + pary[t_SegmentIndex_ub - 1U];
    } else {
      t_Y_d = pary[t_SegmentIndex_ub - 1U];
    }
  }

  return t_Y_d;
}
}  // namespace control
}  // namespace century
