scheduler_conf {
  policy: "classic"
  process_level_cpuset: "0-7"
  threads: [
      {
          name: "shm_disp"
          cpuset: "0-7"
          policy: "SCHED_FIFO"
          prio: 10
      }
  ]
  classic_conf {
    groups: [
      {
        name: "critical_control"
        processor_num: 2
        affinity: "range"
        cpuset: "0-7"
        processor_policy: "SCHED_FIFO"
        processor_prio: 50
        tasks: [
          {
            name: "canbus_/century/control"
            prio: 10
          }
        ]
      },
      {
        name: "normal_control"
        processor_num: 6
        affinity: "range"
        cpuset: "0-7"
        processor_policy: "SCHED_RR"
        processor_prio: 50
        tasks: [
          {
            name: "control_/century/planning"
            prio: 10
          },
          {
            name: "control_/century/loc/pose"
            prio: 10
          },
          {
            name: "control_/century/monitor/monitor_data_aarch"
            prio: 10   
          }
        ]
      }
    ]
  }
}