run_mode_conf {
    run_mode: MODE_REALITY
    clock_mode: MODE_CYBER
}

scheduler_conf {
    policy: "choreography"
    routine_num: 100
    process_level_cpuset: "1-7"
    threads: [
        {
            name: "shm_disp"
            cpuset: "1-7"
            policy: "SCHED_RR"
            prio: 60
        }
    ]
    choreography_conf {
        choreography_processor_num: 6
        choreography_affinity: "range"
        choreography_cpuset: "1-7"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 50

        pool_processor_num: 2
        pool_affinity: "range"
        pool_cpuset: "1-7"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 45

        tasks {
            name: "HeliosFrontLeft"
            prio: 18
        }
        tasks {
            name: "HeliosRearRight"
            prio: 18
        }
        tasks {
            name: "BpFrontLeft"
            prio: 18
        }
        tasks {
            name: "BpFrontRight"
            prio: 18
        }
        tasks {
            name: "BpRearLeft"
            prio: 18
        }
        tasks {
            name: "BpRearRight"
            prio: 18
        }
        tasks {
            name: "LidarObstacleDetection"
            prio: 19
        }
        tasks {
            name: "LidarFreespace"
            prio: 16
        }
    }
}
