scheduler_conf {
    policy: "choreography"
    process_level_cpuset: "2-3"
    threads: [
        {
            name: "shm_disp"
            cpuset: "2"
            policy: "SCHED_RR"
            prio: 45
        }
    ]
    choreography_conf {
        choreography_processor_num: 1
        choreography_affinity: "1to1"
        choreography_cpuset: "3"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 45

        pool_processor_num: 1
        pool_affinity: "1to1"
        pool_cpuset: "2"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 35

        tasks: [
            {
                name: "canbus_/century/control"
                processor: 0
                prio: 11
            }
        ]
    }
}
