scheduler_conf {
  policy: "choreography"
  process_level_cpuset: "0-7"

  choreography_conf {
    choreography_processor_num: 8
    choreography_affinity: "1to1"
    choreography_cpuset: "0-7"
    choreography_processor_policy: "SCHED_RR"
    choreography_processor_prio: 65

    pool_processor_num: 2
    pool_affinity: "range"
    pool_cpuset: "6-7"
    pool_processor_policy: "SCHED_RR"
    pool_processor_prio: 55

    tasks: [
      {
        name: "velodyne_128_convert"
        processor: 4
        prio: 11
      },
      {
        name: "velodyne128_compensator"
        processor: 5
        prio: 12
      },
      {
        name: "velodyne_16_front_center_convert"
        processor: 6
      },
      {
        name: "velodyne_fusion"
        processor: 6
        prio: 2
      },
      {
        name: "velodyne16_fusion_compensator"
        processor: 6
        prio: 3
      },
      {
        name: "velodyne_16_rear_left_convert"
        processor: 4
        prio: 10
      },
      {
        name: "velodyne_16_rear_right_convert"
        processor: 5
        prio: 10
      },
      {
        name: "Velodyne128Detection"
        processor: 6
        prio: 18
      },
      {
        name: "Velodyne16Detection"
        processor: 6
        prio: 18
      },
      {
        name: "RecognitionComponent"
        processor: 6
        prio: 18
      },
      {
        name: "SensorFusion"
        processor: 6
        prio: 18
      },
      {
        name: "prediction"
        processor: 2
        prio: 19
      },
      {
        name: "planning"
        processor: 3
        prio: 17
      },
      {
        name: "routing"
        processor: 2
      },
      {
        name: "planning_/century/routing_response"
        processor: 2
      },
      {
        name: "planning_/century/perception/traffic_light"
        processor: 3
        prio: 17
      },
      {
        name: "msf_localization"
        processor: 0
      },
      {
        name: "rtk_localization"
        processor: 0
      },
      {
        name: "msf_localization_/century/sensor/lidar64/compensator/PointCloud2"
        processor: 1
        prio: 4
      },
      {
        name: "camera_front_6mm_compress"
        processor: 7
        prio: 3
      },
      {
        name: "camera_front_12mm_compress"
        processor: 7
        prio: 3
      },
      {
        name: "camera_left_fisheye_compress"
        processor: 7
        prio: 3
      },
      {
        name: "camera_right_fisheye_compress"
        processor: 7
        prio: 3
      },
      {
        name: "camera_rear_6mm_compress"
        processor: 7
        prio: 3
      }
    ]
  }
}
