scheduler_conf {
    policy: "choreography"
    routine_num: 80
    process_level_cpuset: "0-1"
    choreography_conf {
        choreography_processor_num: 1
        choreography_affinity: "1to1"
        choreography_cpuset: "0"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 60

        pool_processor_num: 1
        pool_affinity: "1to1"
        pool_cpuset: "1"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 50

        tasks: [
            {
                name: "planning"
                processor: 0
                prio: 10
            }
        ]
    }
}
