scheduler_conf {
    policy: "choreography"
    routine_num: 40
    process_level_cpuset: "4"
    choreography_conf {
        choreography_processor_num: 1
        choreography_affinity: "1to1"
        choreography_cpuset: "4"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 30

        pool_processor_num: 1
        pool_affinity: "1to1"
        pool_cpuset: "4"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 20
    }
}
