run_mode_conf {
    run_mode: MODE_REALITY
    clock_mode: MODE_CYBER
}

scheduler_conf {
    policy: "choreography"
    routine_num: 100
    process_level_cpuset: "0-7"
    threads: [
        {
            name: "shm_disp"
            cpuset: "0-7"
            policy: "SCHED_RR"
            prio: 80
        }
    ]
    choreography_conf {
        choreography_processor_num: 6
        choreography_affinity: "range"
        choreography_cpuset: "0-7"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 95

        pool_processor_num: 2
        pool_affinity: "range"
        pool_cpuset: "0-7"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 90

        tasks: [
            {
                name: "HeliosFrontLeft"
                prio: 12
            },
            {
                name: "HeliosRearRight"
                prio: 12
            },
            {
                name: "BpFrontLeft"
                prio: 12
            },
            {
                name: "BpFrontRight"
                prio: 12
            },
            {
                name: "BpRearLeft"
                prio: 12
            },
            {
                name: "BpRearRight"
                prio: 12
            },
            {
                name: "LidarObstacleDetection"
                prio: 20
            },
            {
                name: "LidarFreespace"
                prio: 16
            }
        ]
    }
}
