#!/bin/bash
# set -x
cd /century/data/bag/
current_date=$(date +"%Y%m%d")
# seven_days_ago=$(date -d "7 days ago" +"%Y%m%d")

# for dir in $(ls -d */ | grep -E "^[0-9]{8}/$" | sed 's#/##'); do
#     if [[ "$dir" < "$seven_days_ago" ]]; then
#         echo "delete dir: $dir"
#         rm -r "$dir"
#     fi
# done

if [[ ! -d ${current_date} ]]; then
  mkdir ${current_date}
fi
cd  ${current_date}

if [ -f /usr/autowin/version ]; then
  DomainController=`cat /usr/autowin/version | grep 'DomainController:' | awk '{print $2}'`
  case "${DomainController}" in
      "slave")  nohup ionice -c 3 nice -n 19 cyber_recorder record -a -i 30 -m 8192 \
      -k /century/sensor/camera/front/image \
      -k /century/sensor/camera/left_front/image \
      -k /century/sensor/camera/left_rear/image \
      -k /century/sensor/camera/rear/image \
      -k /century/sensor/camera/right_front \
      -k /century/sensor/camera/right_rear/image > /dev/null 2>&1 & ;;
      "slave")  nohup env CYBER_PROCESS_GROUP=recorder_sched cyber_recorder record -a "${RAW_CAMERA_BLACKLIST[@]}" -i 30 -m 8192 > /dev/null 2>&1 & ;;
      "master") nohup env CYBER_PROCESS_GROUP=recorder_sched cyber_recorder record -a -i 60 -m 8192 -k /century/debug/perception/obstacles > /dev/null 2>&1 &;;
  esac
fi
