--flagfile=/century/modules/common/data/global_flagfile.txt
--routing_conf_file=/century/modules/routing/conf/routing_config.pb.txt
--routing_point_file=/century/modules/routing/conf/routing_point.pb.txt
--project_scenario=QDG
#--use_road_id=false

# lane search
--routing_lane_search_radius=0.3
--lane_search_loop_count=20
--lane_search_increment=1.0
--max_nearest_lane_l_buffer=5.5
--max_lane_search_distance=30
--routing_junction_search_radius=0.5

# adc lane matching
--adc_lane_range=3.5
--min_adc_lane_range=1.0
--adc_black_lane_range=1.3
--adc_lane_heading_diff=0.5
--adc_advance_distance=30.0
--max_heading_diff=2.5
--min_heading_diff=0.2

# vehicle
--vehicle_length=15.0

# lane change
--min_length_for_lane_change=1.0
--enable_change_lane_in_result=true
--enable_prefer_lane_change=true
--enable_all_prefer_lane_change=true
--enable_lane_change_length_determination=true
--enable_lane_change_close_distance_check=false
--lane_change_distance=35.0
--min_lane_change_length=10.0
--lane_change_length=15.0

# passage extension
--enable_extend_passage=false
--enable_extend_passage_junction=false
--min_length_for_extend_passage_lane_change=100.0

# routing strategy
--enable_routing_turn_around_flag=false
--enable_search_more_routing_flag=true
--enable_shortest_path_non_replan=true
--enable_full_path_twoway_driving=true
--enable_loop_running=true
--enable_only_u_turn=false
--enable_default_shortest_path_output=true
--max_number_responses_output=3
--enable_multi_mode_tiny_adjustment=true
--enable_tiny_along_lane=true
--index_offset=100

# route selection
--min_route_distance_diff=3.5
--max_route_distance_diff=5.0
--reverse_type_cost=100.0

# rerouting
--rerouting_distance=60.0
--max_rerouting_times=3
--rerouting_length_diff=100.0
--routing_response_history_interval_ms=1000
--routing_request_interval_ms=1000

# two-point routing
--junction_two_point_distance=50.0
--adc_two_point_distance=2.0
--two_point_distance=75.0

# human-shaped driver
--enable_huaman_shaped_driver=true
--human_shape_distance=17.0
--human_shape_midlle_distance=24.0
--human_shape_max_distance=1250000.0

# blacklisted lanes
--enable_add_blacklisted_lanes=true
--max_blacklisted_lane_distance=65.0
--min_blacklisted_lane_distance=50.0
--d7j4w_blacklisted_lane_distance=40.0

# yard & stacker
--enable_yard_static_wait_distance=true
--yard_static_wait_distance=35.0
--dual_box_exit_distance=20.0
--max_stacker_position_distance=30
--reach_stacker_projection_distance_threshold=1.0
--enable_reach_stacker_end_projection=false

# fixed heading
--j4_east_fixed_heading=-0.18
--j4_west_fixed_heading=2.94
--demo_heading=-0.08

# dongjiazhen
--enable_add_djz_blacklisted_lanes=false
--enable_djz_handing_dead_end=true
--djz_max_blacklisted_lane_distance=65.0
--enable_DJZ_demonstrate=false
# 0: push forward 60m, 1: max_lane_change, 2: min_lane_change
--DJZ_demonstrate_scheme=2
--DJZ_demonstrate_move_disatnce=64.0
--DJZ_demonstrate_max_lane_change_disatnce=35.0
--DJZ_demonstrate_min_lane_change_disatnce=15.0
