# Global TCP buffer config
# buf = clamp(max_msg_size * 4, default_buf, max_buf)

default_buf: 262144    # 256KB
max_buf: 16777216      # 16MB


channel_conf {
  channel_name: "/century/sensor/camera/front/image/compressed"
  max_msg_size: 819200
}

channel_conf {
  channel_name: "/century/sensor/camera/left_front/image/compressed"
  max_msg_size: 819200
}

channel_conf {
  channel_name: "/century/sensor/camera/left_rear/image/compressed"
  max_msg_size: 819200
}

channel_conf {
  channel_name: "/century/sensor/camera/rear/image/compressed"
  max_msg_size: 819200
}

channel_conf {
  channel_name: "/century/sensor/camera/right_front/image/compressed"
  max_msg_size: 819200
}

channel_conf {
  channel_name: "/century/sensor/camera/right_rear/image/compressed"
  max_msg_size: 819200
}

channel_conf {
  channel_name: "/lidar/bp/front_left"
  max_msg_size: 1572864
}

channel_conf {
  channel_name: "/lidar/bp/front_right"
  max_msg_size: 1572864
}

channel_conf {
  channel_name: "/lidar/bp/rear_left"
  max_msg_size: 1572864
}

channel_conf {
  channel_name: "/lidar/bp/rear_right"
  max_msg_size: 1572864
}

channel_conf {
  channel_name: "/lidar/helios/front_left"
  max_msg_size: 1572864
}

channel_conf {
  channel_name: "/lidar/helios/rear_right"
  max_msg_size: 1572864
}

# channel_conf { channel_name: "channel/chatter_0" max_msg_size: 2097152 }

