whitelist_channels: "/century/inner/perception/obstacles"
whitelist_channels: "/century/loc/pose"
whitelist_channels: "/century/perception/around_ego/obstalces"
whitelist_channels: "/century/prediction"
whitelist_channels: "/century/perception/obstacles"
