/******************************************************************************
 * Copyright 2017 The Century Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

/**
 * @file
 * @brief Defines the PPController class.
 */

#pragma once

#include <fstream>
#include <memory>
#include <string>

#include "Eigen/Core"
#include "modules/common/configs/proto/vehicle_config.pb.h"
#include "modules/common/filters/digital_filter.h"
#include "modules/common/filters/digital_filter_coefficients.h"
#include "modules/common/filters/mean_filter.h"
#include "modules/control/common/interpolation_1d.h"
#include "modules/control/common/leadlag_controller.h"
#include "modules/control/common/mrac_controller.h"
#include "modules/control/common/trajectory_analyzer.h"
#include "modules/control/controller/controller.h"

/**
 * @namespace century::control
 * @brief century::control
 */

 namespace century {
 namespace control {
 
 /**
  * @class PPController
  * @brief Pure Pursuit controller, to compute steering target.
  */
 
 class PPController : public Controller {
  public:
   /**
    * @brief constructor
    */
   PPController();

   /**
    * @brief destructor
    */
   virtual ~PPController();

   /**
    * @brief initialize Pure Pursuit Controller
    * @param control_conf control configurations
    * @return Status initialization status
    */
   common::Status Init(std::shared_ptr<DependencyInjector> injector,
                       const ControlConf *control_conf) override;

   /**
    * @brief compute steering target based on current vehicle status
    *        and target trajectory
    * @param localization vehicle location
    * @param chassis vehicle status e.g., speed, acceleration
    * @param trajectory trajectory generated by planning
    * @param cmd control command
    * @return Status computation status
    */
   common::Status ComputeControlCommand(
       const localization::LocalizationEstimate *localization,
       const canbus::Chassis *chassis, const planning::ADCTrajectory *trajectory,
       const planning::AebResult *aeb_result,
       ControlCommand *cmd) override;

   /**
    * @brief reset Pure Pursuit Controller
    * @return Status reset status
    */
   common::Status Reset() override;

   /**
    * @brief stop Pure Pursuit Controller
    */
   void Stop() override;

   /**
    * @brief Pure Pursuit controller name
    * @return string controller name in string
    */
   std::string Name() const override;

  protected:

   /**
    * @brief load control configuration
    * */
   bool LoadControlConf(const ControlConf *control_conf);

   /**
    * @bief compute control error
    * */
   void UpdateState(SimpleLateralDebug *debug);

   /**
    * @brief compute lateral error
    * */
   void ComputeLateralErrors(const double x, const double y, const double theta,
                             const double linear_v, const double angular_v,
                             const double linear_a,
                             const TrajectoryAnalyzer &trajectory_analyzer,
                             SimpleLateralDebug *debug);

   /**
    * @brief log parameter
    * */
   void LogInitParameters();

   /**
    * @brief update driving heading
    * */
   void UpdateDrivingOrientation();

   /**
    * @brief output log
    * */
   void ProcessLogs(const SimpleLateralDebug *debug,
                    const canbus::Chassis *chassis);

   /**
    * @brief close log file
    * */
   void CloseLogFile();

   /*
    * @brief filter steer cmd
    * @param steer
    */
   double FilterCmd(const double steer);

   // controller configuration
   const ControlConf *control_conf_ = nullptr;

   // vehicle parameter
   common::VehicleParam vehicle_param_;

   // control cycle
   double ts_ = 0.0;

   double lookahead_station_low_speed_ = 0.0;

   double lookback_station_low_speed_ = 0.0;

   double lookahead_station_high_speed_ = 0.0;

   double lookback_station_high_speed_ = 0.0;

   double min_lookahead_station_ = 0.0;

   double velocity_ratio_ = 0.0;

   double curvature_ratio_ = 0.0;

   double lateral_error_ratio_ = 0.0;

   double heading_error_ratio_ = 0.0;

   double long_ld_lateral_error_threshold_ = 0.0;

   // a proxy to analyze the planning trajectory
   TrajectoryAnalyzer trajectory_analyzer_;

   double previous_lateral_acceleration_ = 0.0;

   double previous_heading_rate_ = 0.0;
   double previous_ref_heading_rate_ = 0.0;

   double previous_heading_acceleration_ = 0.0;
   double previous_ref_heading_acceleration_ = 0.0;

   double wheelbase_ = 0.0, half_wheelbase_ = 0.0;

   const std::string name_;

   double steer_limit_ = 0.0;

   double min_radius_ = 0.0;

   double angular_velocity_threshold_ = 0.0;

   double query_relative_time_ = 0.0;

   double last_preview_s_ = 0.0;

   double heading_weight_ = 0.0;

   // driving heading
   double driving_orientation_ = 0.0;

   double low_speed_bound_ = 0.0;

   double low_speed_window_ = 0.0;

   std::ofstream steer_log_file_;

   std::shared_ptr<DependencyInjector> injector_;

   common::MeanFilter cmd_filter_;

   std::deque<double> last_cmd_queue_;

   canbus::Chassis::GearPosition last_gear_position_ = canbus::Chassis::GEAR_NONE;

};

}
}
