--flagfile=/century/modules/common/data/global_flagfile.txt
--canbus_conf_file=/century/modules/canbus/conf/canbus_conf.pb.txt
--noenable_chassis_detail_pub
--noreceive_guardian
--enable_monitor_control=true
--enable_canbus_thread=true
--enable_canbus_debug_flag=false


