transport_conf {
     communication_mode {
         same_proc: INTRA
         diff_proc: SHM
         diff_host: SHM
     }
}

run_mode_conf {
    run_mode: MODE_REALITY
    clock_mode: MODE_CYBER
}

scheduler_conf {
    policy: "choreography"
    routine_num: 50
    process_level_cpuset: "0-2"
    choreography_conf {
        choreography_processor_num: 1
        choreography_affinity: "1to1"
        choreography_cpuset: "0"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 60

        pool_processor_num: 2
        pool_affinity: "1to1"
        pool_cpuset: "1-2"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 50
    }
}
