scheduler_conf {
    policy: "choreography"
    process_level_cpuset: "0-7"
    threads: [
        {
            name: "async_log"
            cpuset: "1"
            policy: "SCHED_RR"
            prio: 5
        }, {
            name: "shm"
            cpuset: "2"
            policy: "SCHED_RR"
            prio: 10
        }
    ]
    choreography_conf {
        choreography_processor_num: 4
        choreography_affinity: "1to1"
        choreography_cpuset: "0-3"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 10

        pool_processor_num: 4
        pool_affinity: "1to1"
        pool_cpuset: "4-7"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 5

        tasks: [
            {
                name: "E"
                processor: 0
                prio: 0
            },
            {
                name: "A"
                processor: 1
                prio: 0
            },
            {
                name: "B"
                processor: 2
                prio: 1
            },
            {
                name: "C"
                processor: 3
                prio: 2
            },
            {
                name: "D"
                processor: 3
                prio: 3
            }
        ]
    }
}
