scheduler_conf {
    policy: "choreography"
    process_level_cpuset: "4-6"
    threads: [
        {
            name: "rs_recv"
            cpuset: "4"
            policy: "SCHED_RR"
            prio: 55
        },
        {
            name: "rs_handle"
            cpuset: "5"
            policy: "SCHED_RR"
            prio: 55
        },
        {
            name: "rs_cloud"
            cpuset: "6"
            policy: "SCHED_RR"
            prio: 55
        }
    ]
    choreography_conf {
        choreography_processor_num: 2
        choreography_affinity: "1to1"
        choreography_cpuset: "4-5"
        choreography_processor_policy: "SCHED_RR"
        choreography_processor_prio: 55

        pool_processor_num: 1
        pool_affinity: "1to1"
        pool_cpuset: "6"
        pool_processor_policy: "SCHED_RR"
        pool_processor_prio: 45
    }
}
