--flagfile=/century/modules/common/data/global_flagfile.txt
--control_conf_file=/century/modules/control/conf/control_conf.pb.txt
--enable_speed_station_preview=false
--enable_interpolation_by_time=false
--use_preview_speed_for_table=true
--enable_gain_scheduler=true
--set_steer_limit=true
--enable_slope_offset=false
--enable_maximum_steer_rate_limit=true
--enable_mass_update_debug = true

--state_transform_to_com_reverse=true
--state_transform_to_com_drive=true
--trajectory_transform_to_com_reverse=true
--trajectory_transform_to_com_drive=true
--enable_feedback_augment_on_high_speed=false
# --reverse_heading_vehicle_state=false
--reverse_heading_control=true

--query_time_nearest_point_only=false
--query_forward_time_point_only=false
# --use_control_submodules=true
--enable_fill_trajectory_point=true
--enable_secondary_filter=true
--minimum_execution_monitor_level=6
--enable_check_monitor_input=true

