--flagfile=/century/modules/common/data/global_flagfile.txt
# --cloud_server_ip=10.135.252.124
--cloud_server_ip=192.168.1.168
--cloud_server_port=50018
--cloud_mqtt_server_ip=10.135.252.124
--cloud_mqtt_server_port=1883
--cloud_mqtt_username=admin
--cloud_mqtt_password=emqx_2025_Kl
--cloud_mqtt_sub_qos_default=1
--cloud_mqtt_pub_qos_default=1
--cloud_mqtt_sub_qos_overrides={}
--cloud_mqtt_pub_qos_overrides={}
# --cloud_server_port=9999
--vehicle_unique_id=XUG0070EVSED01093
--vehicle_id=KL007
